initial-scaffolding
unawaretub86/MoneyTracker pull request #1
Opened 2024-05-13 22:31 UTC by unawaretub86

2024-05-13 22:41 UTC, yipson commented on internal/domain/money-tracker/repository/database/yourDomain.go
> +package database
please review

2024-05-13 22:43 UTC, yipson requested changes
please review the database folder

2024-05-13 22:43 UTC, yipson commented on internal/domain/money-tracker/repository/yourDomain.go
> +package repository
please review

2024-05-14 00:36 UTC, unawaretub86 commented
localhost:8080/ping

{
    "response": "pong"
}

![image](https://github.com/unawaretub86/MoneyTracker/assets/79619416/a18c08c7-d0d8-4c5f-82d3-65ee8a20043d)

2024-05-14 00:56 UTC, yipson approved these changes

2024-05-14 00:57 UTC, merged